### ISSUE TITLE
expo-server-sdk-java v1.1.0 causes com.fasterxml.jackson version incompatibility

### ISSUE THREAD

**Issue by kpukharev** [jav/expo-server-sdk-java#42]
I use Spring Boot 2.7.7, with the built-in com.fasterxml.jackson. 
I added a pom dependency:

```
<dependency>
	<groupId>io.github.jav</groupId>
	<artifactId>expo-server-sdk</artifactId>
	<version>1.1.0</version>
</dependency>
```

And I started getting an error:

```
Caused by: java.lang.NoSuchMethodError: 'boolean com.fasterxml.jackson.databind.SerializationConfig.hasExplicitTimeZone()'
	at com.fasterxml.jackson.datatype.jsr310.ser.InstantSerializerBase.formatValue(InstantSerializerBase.java:145) ~[jackson-datatype-jsr310-2.13.4.jar:2.13.4]
	at com.fasterxml.jackson.datatype.jsr310.ser.InstantSerializerBase.serialize(InstantSerializerBase.java:105) ~[jackson-datatype-jsr310-2.13.4.jar:2.13.4]
	at com.fasterxml.jackson.datatype.jsr310.ser.ZonedDateTimeSerializer.serialize(ZonedDateTimeSerializer.java:79) ~[jackson-datatype-jsr310-2.13.4.jar:2.13.4]
	at com.fasterxml.jackson.datatype.jsr310.ser.ZonedDateTimeSerializer.serialize(ZonedDateTimeSerializer.java:13) ~[jackson-datatype-jsr310-2.13.4.jar:2.13.4]
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728) ~[expo-server-sdk-1.1.0.jar:na]
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:755) ~[expo-server-sdk-1.1.0.jar:na]
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178) ~[expo-server-sdk-1.1.0.jar:na]
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serializeContents(CollectionSerializer.java:145) ~[expo-server-sdk-1.1.0.jar:na]
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serialize(CollectionSerializer.java:107) ~[expo-server-sdk-1.1.0.jar:na]
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serialize(CollectionSerializer.java:25) ~[expo-server-sdk-1.1.0.jar:na]
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480) ~[expo-server-sdk-1.1.0.jar:na]
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:400) ~[expo-server-sdk-1.1.0.jar:na]
	at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1512) ~[expo-server-sdk-1.1.0.jar:na]
	at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:1006) ~[expo-server-sdk-1.1.0.jar:na]
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.writeInternal(AbstractJackson2HttpMessageConverter.java:456) ~[spring-web-5.3.24.jar:5.3.24]
	at org.springframework.http.converter.AbstractGenericHttpMessageConverter.write(AbstractGenericHttpMessageConverter.java:104) ~[spring-web-5.3.24.jar:5.3.24]
	at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:290) ~[spring-webmvc-5.3.24.jar:5.3.24]
	at org.springframework.web.servlet.mvc.method.annotation.HttpEntityMethodProcessor.handleReturnValue(HttpEntityMethodProcessor.java:219) ~[spring-webmvc-5.3.24.jar:5.3.24]
	at org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:78) ~[spring-web-5.3.24.jar:5.3.24]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:135) ~[spring-webmvc-5.3.24.jar:5.3.24]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.3.24.jar:5.3.24]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.24.jar:5.3.24]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.24.jar:5.3.24]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1071) ~[spring-webmvc-5.3.24.jar:5.3.24]
	... 94 common frames omitted
```

This error is not explicitly related to expo server library's functionality. As it's seen from the log it happens when `spring-boot-starter-web` is preparing an HTTP response, converting Pojo into JSON. Although I have noticed that somehow it started to use Jaskson from expo-server-sdk-1.1.0.jar, like at the end of this line: `at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:1006) ~[expo-server-sdk-1.1.0.jar:na]`. So there's definitely an incompatibility between the libraries.

So I have tried to
1. Downgrade expo-server-sdk-java to 1.0.0
2. Exclude com.fasterxml.jackson from expo-server-sdk-java, like this

```
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-web</artifactId>
	<exclusions>
		<exclusion>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-core</artifactId>
		</exclusion>
		<exclusion>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
		</exclusion>
		<exclusion>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-annotations</artifactId>
		</exclusion>
	</exclusions>
</dependency>
```

Unfortunately none of those have fixed the error.
The error disappears when I remove `expo-server-sdk-java` from the project.

**Comment by jav** [comment]
Hi!

I've stopped maintaining this repository!
Maintenance was taken over by @oliverwelter in [this repository](https://github.com/nia-medtech/expo-server-sdk-java).

I suggest opening an issue there!

Best of luck!
